### ISSUE TITLE
Infografia Fases de la Gestion de Proyectos

### ISSUE THREAD

**Issue by AndreLuna6** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-AndreLuna6#2]
[InfografiaU1_AndreEmmanuelLunaGonzalez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-AndreLuna6/files/9418940/InfografiaU1_AndreEmmanuelLunaGonzalez.pdf)

**Comment by bg55-a** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
